name: Auto-merge Dependabot PRs
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
  pull-requests: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.11.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: major           # auto-merge patch + minor updates
          merge-method: squash    # or merge/rebase
 
